### ISSUE TITLE
Which version of PHH 10 to use after flashing Lineage 17.0

### ISSUE THREAD

**Issue by stevea76** [PeterCxy/android_device_ktouch_i9#1]
Hi, this is more of a query than an issue, firstly fantastic work with the i9, I flashed your Lineage 17.0 and it is working great. I am a little confused which version of PHH 10 to flash after I have installed Lineage 17.0
I went from stock i9 firmware, then flashed the SAR twrp, then Lineage 17.0  then PHH 10 arm64 A/B using fastboot (there is no option to flash a system image in twrp). 
The phone remains on the k-touch logo screen after fastboot flash of PHH 10 (A/B). 
Many thanks.

**Comment by PeterCxy** [comment]
Just like before, the system partition of this device is still not large enough to fit an unmodified phh GSI image. Flashing an 2-stage-init boot image doesn't help in this aspect. You still need to shrink the system image before it can work on this device.

To use phh GSI again, you can return back to stock boot.img (which I hope you have a copy of) and flash the phh GSI you used before coming to LOS17 (presumably the one phh or I provided).

**Comment by stevea76** [comment]
Many thanks for your reply.
